/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package javalin.webapp

import io.javalin.Javalin
import NLP_ITB.POSTagger.HMM.Decoder.MainTagger
import java.nio.file.Paths

class App {
    companion object {
        private fun getPath(): String {
            return App::class.java.protectionDomain.codeSource.location.path
        }

        fun getResourcePath(): String {
            return Paths.get(this.getPath(), "..", "resource")
                    .normalize()
                    .toAbsolutePath()
                    .toString()
        }
    }

}

fun main(args: Array<String>) {
    val app = Javalin.create().start(7000)

    val tagger = getTagger()

    app.post("/") { ctx ->
        val text = ctx.formParam("text")?.replace("\n", " ")
        ctx.json(object {
            val text = tagger.tagText(text).joinToString(" ")
        })
    }
}

fun getTagger(): MainTagger {
    return MainTagger(
            Paths.get(App.getResourcePath(), "Lexicon.trn").toString(),
            Paths.get(App.getResourcePath(), "Ngram.trn").toString(),
            1,
            3,
            3,
            0,
            1,
            false,
            0.2,
            0,
            500.0,
            1
    )
}
